### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by yuan-zm** [weiliu-ai/uada#2]
Hi, I was confused about the detach operation when I read your code.
https://github.com/weiliu-ai/auda/blob/68288a50b78805cab82b91572118d97f04caa8a1/xmuda/train_auda.py#L328

Could you please give a detail explain?

**Comment by weiliu-ai** [comment]
Sorry to confuse you. I haven't dealt with this code in a year and a half.

**Comment by weiliu-ai** [comment]
> Sorry to confuse you. I haven't dealt with this code in a year and a half.
