### ISSUE TITLE
Code for visualization

### ISSUE THREAD

**Issue by Feynben** [weiliu-ai/uada#3]
Thanks for your great contributions! Could you release the code for visualization or give us some details about the visualization? Thanks !

**Comment by weiliu-ai** [comment]
Sorry, I cannot find the code file now.  The file visualize.py may be helpful.
[https://github.com/valeoai/xmuda/blob/8b39f8f77f048cd4c086323dd89fbf9710335d35/xmuda/data/nuscenes/nuscenes_dataloader.py](url)
I think you could  visualize the results  with the help of functions such as _draw_points_image_labels_.
